version: 2

models:
  - name: q1
    columns:
      - name: id
      - name: text
  - name: q2
    columns:
      - name: year
      - name: month
      - name: count
  - name: q3
    columns:
      - name: src
      - name: dst

